import Handlebars from 'handlebars';
import * as Components from './components';
import { navigate } from './core/navigate';
import { registerComponent } from './core/resgiterComponent';

Handlebars.registerPartial('Form', Components.Form);
Handlebars.registerPartial('Tooltip', Components.Tooltip);
Handlebars.registerPartial('Modal', Components.Modal);
document.addEventListener('DOMContentLoaded', () => navigate('allPages'));
registerComponent('Button', Components.Button);
registerComponent('InputField', Components.InputField);
registerComponent('Input', Components.Input);
registerComponent('SearchField', Components.SearchField);
registerComponent('ChatCard', Components.ChatCard);
registerComponent('MessageHeader', Components.MessageHeader);
registerComponent('Message', Components.Message);
registerComponent('MessageField', Components.MessageField);
registerComponent('ProfileInput', Components.ProfileInput);
registerComponent('ProfileButton', Components.ProfileButton);
registerComponent('ErrorLine', Components.ErrorLine);
registerComponent('MessageSend', Components.MessageSend);
